TRAIN:
  ENABLE: False # change
  # DATASET: kinetics
  DATASET: rrl
  BATCH_SIZE: 4
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/i3d/checkpoint/I3D_8x8_R50.pkl # change
  CHECKPOINT_TYPE: caffe2  # change
  # TRAIN_HEAD_ONLY: False # change
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/i3d/checkpoint/clean_label/split_0/midlevel/checkpoints/head_only_epoch_5.pyth # change
DATA:
  DECODING_BACKEND: pyav
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /cvhci/temp/lfan/label/noisy_50/split_0/midlevel  # change
  PATH_PREFIX: /cvhci/temp/lfan/clip  # change
  TRAIN_CROP_NUM_TEMPORAL: 2  # default 1
  TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  SSL_MOCOV2_AUG: True # default false
  SSL_COLOR_JITTER: True # default false
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-4 # change
  LR_POLICY: cosine
  MAX_EPOCH: 30 # change
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.01 # change
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 5e-5
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 34 # change
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  # LOSS_FUNC: elr_loss
  DROPOUT_RATE: 0.5
  BETA: 0.9
  LAM: 1
TEST:
  ENABLE: True  # change
  # DATASET: kinetics
  DATASET: rrl
  BATCH_SIZE: 16
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/i3d/checkpoint/clean_label/split_0/midlevel/checkpoints/checkpoint_epoch_00025.pyth
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /cvhci/temp/lfan/i3d/checkpoint/noisy_50_rrl/split_0/midlevel_noaug_simclr_wpro1_onlylow0.04_high0.999
TENSORBOARD:
  ENABLE: True