TRAIN:
  # ENABLE: True  # change
  ENABLE: False
  # DATASET: kinetics
  DATASET: rrl
  BATCH_SIZE: 4  # change
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/mvitv2/checkpoint/MViTv2_S_16x4_k400_f302660347.pyth  # change
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/mvitv2/checkpoint/clean_label/split_1/midlevel/checkpoints/head_only_epoch_5.pyth # change
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/mvitv2/checkpoint/noisy_50_idfd/split_1/midlevel_fuzzyc_e30_tau0.5/checkpoints/checkpoint_best.pyth # change
  CHECKPOINT_EPOCH_RESET: True
  # TRAIN_HEAD_ONLY: True # change
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: pyav
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_CROP_NUM_TEMPORAL: 2  # default 1
  TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  SSL_MOCOV2_AUG: True # default false
  SSL_COLOR_JITTER: True # default false
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: /cvhci/temp/lfan/label/noisy_50/split_1/midlevel  # change
  PATH_PREFIX: /cvhci/temp/lfan/clip  # change
  # TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_SCALES_RELATIVE: [0.2, 0.766]  # Change to ssl mode
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 16
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: True
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 2, 2], [2, 1, 1, 1], [3, 1, 2, 2], [4, 1, 1, 1], [5, 1, 1, 1], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 2, 2], [15, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
AUG:
  NUM_SAMPLE: 1
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: False
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 1e-4  # change
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 5e-5 # change
  WARMUP_EPOCHS: 5.0 # change
  LR_POLICY: cosine
  MAX_EPOCH: 35  # change
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05  
  OPTIMIZING_METHOD: adamw
MODEL:
  NUM_CLASSES: 34  # change
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  # LOSS_FUNC: elr_loss
  DROPOUT_RATE: 0.5  # default 0.5
BETA: 0.5
LAM: 1.0
# CLUSTER: fuzzyc
CLUSTER: agglomerative
# CLUSTER: spectral
SAMPLE_SELECTION: soft_label_wo_class_weights
# SAMPLE_SELECTION: jsd
NOISE_PROP: 0.5
LAM_U: 100
TEST:
  ENABLE: True # change
  # DATASET: kinetics
  DATASET: rrl
  BATCH_SIZE: 4  # change
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5
  SAVE_RESULTS_PATH: test_pred.csv
  CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/mvitv2/checkpoint/noisy_50_crl/split_1/midlevel_from_idfd_soft_labels_clwe_lam0.0_l2noise_w5e35_nomixup_afterwp/checkpoints/checkpoint_best.pyth
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/mvitv2/checkpoint/noisy_50_idfd/split_1/midlevel_fuzzyc_e30_tau0.5/checkpoints/checkpoint_best.pyth
DATA_LOADER:
  NUM_WORKERS: 4  
  PIN_MEMORY: True
NUM_GPUS: 1  
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /cvhci/temp/lfan/mvitv2/checkpoint/noisy_50_crl/split_1/midlevel_from_idfd_soft_labels_l2noise_w5e35_nomixup_afterwp
TENSORBOARD:
  ENABLE: True
# TASK: TSNE 