TRAIN:
  # ENABLE: False # default True
  DATASET: kinetics
  # DATASET: rrl
  BATCH_SIZE: 2
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/checkpoint/x3d_m.pyth # change
  CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/DAD/clean_label/binary/checkpoints/head_only_epoch_5.pyth
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/checkpoint/noisy_50_idfd/split_2/midlevel_fuzzyc_tau0.5_e30/checkpoints/checkpoint_best.pyth
  CHECKPOINT_EPOCH_RESET: True
  # TRAIN_HEAD_ONLY: True # change
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: kinetics
  # DATASET: rrl
  BATCH_SIZE: 4
  # CHECKPOINT_FILE_PATH: 'x3d_m.pyth' # 76.21% top1 30-view accuracy to download from the model zoo (optional).
  NUM_SPATIAL_CROPS: 1
  # NUM_SPATIAL_CROPS: 3
  NUM_ENSEMBLE_VIEWS: 5
  SAVE_RESULTS_PATH: test_pred.csv
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/checkpoint/noisy_50_crl/split_1/midlevel_from_idfd_soft_labels_per_class_clwe_lam0.0_l2noise_w5e35/checkpoints/checkpoint_best.pyth
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/DAD/clean_label/head_only/checkpoints/checkpoint_epoch_00005.pyth
DATA:
  DECODING_BACKEND: pyav
  # PATH_TO_DATA_DIR: /cvhci/temp/lfan/label/noisy_50/split_1/midlevel  # change
  # PATH_PREFIX: /cvhci/temp/lfan/clip  # change
  PATH_TO_DATA_DIR: /lsdf/data/activity/DAD/label/clean_label/binary  # change
  PATH_PREFIX: /lsdf/data/activity/DAD/video_t/clips  # change
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224 # use if TEST.NUM_SPATIAL_CROPS: 1
  # TEST_CROP_SIZE: 256 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  # USE_OFFSET_SAMPLING: True
  # TRAIN_CROP_NUM_TEMPORAL: 2  # default 1
  # TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  # SSL_MOCOV2_AUG: True # default false
  # SSL_COLOR_JITTER: True # default false
  # COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  # SSL_COLOR_HUE: 0.15
  # SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
AUG:
  NUM_SAMPLE: 2  # change
  ENABLE: True  # change
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.01 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 25
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 5e-5
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 2
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  # LOSS_FUNC: elr_loss
  DROPOUT_RATE: 0.5
BETA: 0.5
LAM: 0.0
CLUSTER: agglomerative
# CLUSTER: fuzzyc
SAMPLE_SELECTION: soft_label
NOISE_PROP: 0.5
LAM_U: 50
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
OUTPUT_DIR: /cvhci/temp/lfan/x3d/DAD/clean_label/binary
TENSORBOARD:
  ENABLE: True
# TASK: TSNE