TRAIN:
  ENABLE: True  # change
  # DATASET: kinetics
  DATASET: rrl
  BATCH_SIZE: 2
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/checkpoint/x3d_l.pyth # change
  CHECKPOINT_FILE_PATH: /cvhci/temp/lfan/x3d/checkpoint/clean_label/split_0/midlevel/checkpoints/head_only_epoch_5.pyth # change
  CHECKPOINT_EPOCH_RESET: True
  # TRAIN_HEAD_ONLY: True # change
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 5.0
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  # DATASET: kinetics
  DATASET: rrl
  BATCH_SIZE: 16
  # CHECKPOINT_FILE_PATH: 'x3d_l.pyth' # 77.48% top1 30-view accuracy to download from the model zoo (optional).
  # NUM_SPATIAL_CROPS: 1
  NUM_SPATIAL_CROPS: 3
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [356, 446]
  TRAIN_CROP_SIZE: 312
  # TEST_CROP_SIZE: 312 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 356 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: pyav
  PATH_TO_DATA_DIR: /cvhci/temp/lfan/label/noisy_50/split_1/midlevel  # change
  PATH_PREFIX: /cvhci/temp/lfan/clip  # change
  TRAIN_CROP_NUM_TEMPORAL: 2  # default 1
  TRAIN_CROP_NUM_SPATIAL: 1  # default 1
  SSL_MOCOV2_AUG: True # default false
  SSL_COLOR_JITTER: True # default false
  COLOR_RND_GRAYSCALE: 0.2 # default 0.0
  SSL_COLOR_HUE: 0.15
  SSL_COLOR_BRI_CON_SAT: [0.6, 0.6, 0.6] # default [0.4, 0.4, 0.4]
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 1e-4 # change  
  BASE_LR_SCALE_NUM_SHARDS: True
  MAX_EPOCH: 25 # change
  LR_POLICY: cosine
  WEIGHT_DECAY: 5e-3  #change 
  WARMUP_EPOCHS: 0.0
  WARMUP_START_LR: 5e-5
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 34 # change
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  # LOSS_FUNC: cdr
  DROPOUT_RATE: 0.5
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 1
RNG_SEED: 0
OUTPUT_DIR: /cvhci/temp/lfan/x3d/checkpoint/noisy_50/split_1/midlevel
TENSORBOARD:
  ENABLE: True
